# wheels control loop PID
front_right_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}
front_left_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}
rear_right_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}
rear_left_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}

lpf: {front_right: 0.2, front_left: 0.2, rear_right: 0.2, rear_right: 0.2}

motor_max_rpm: 150