# wheels control loop PID
front_right_wheel_joint: {p: 1.0, i: 1.0, d: 0.0, i_max: 10.0, i_min: -10.0}
front_left_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}
rear_right_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}
rear_left_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0}

motor_max_rpm: 150